- src/Microsoft.VisualStudio.Threading.Analyzers.NuGet/version.json
- src/Microsoft.VisualStudio.Threading.Analyzers/version.json
Till we change the IDs and vet them a bit more, our analyzers package should claim to be `-beta`
> Put analyzers in -beta quality

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSSDK012SpecifyJtfWhereAllowedTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK012SpecifyJtfWhereAllowed.cs
When installing these analyzers to the VS source tree, I discovered that using the `JTF.RunAsync(VsTaskRunContext, Func<Task>)` extension method would cause VSSDK012 to fire since no argument was supplied for the JTF (since it is the implicit receiver of the method call when used with extension method syntax.
This fixes that bug by recognizing that we should skip first parameters of extension methods when looking for overloads that accept JTF.
> Fix mis-fire of VSSDK012 when JTF is the receiver of an extension method

- doc/analyzers/VSSDK014.md
- doc/analyzers/index.md
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSSDK014AvoidLegacyThreadSwitchingAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/Namespaces.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK014AvoidLegacyThreadSwitchingAnalyzer.cs
Switching to the UI thread should be done using `JoinableTaskFactory.SwitchToMainThreadAsync`
rather than legacy methods such as `Dispatcher.Invoke` or `ThreadHelper.Invoke`.
This avoids deadlocks and can reduce threadpool starvation.
```csharp
void Foo() {
ThreadHelper.Generic.Invoke(delegate {
DoSomething();
});
}
```
Use `await SwitchToMainThreadAsync()` instead, wrapping with `JoinableTaskFactory.Run` if necessary:
```csharp
void Foo() {
ThreadHelper.JoinableTaskFactory.Run(async delegate {
await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
DoSomething();
});
}
```
> Add VSSDK014 "Avoid legacy thread switching" analyzer

- src/Microsoft.VisualStudio.Threading.Shared/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading.Tests.Shared/JoinableTaskTests.cs
The JoinAsync method would capture the context of its caller and require it to complete after its underlying JoinableTask completes. This is inefficient since completing should not require this SynchronizationContext.
Theoretically (and as the two new tests demonstrated) it could also lead to deadlocks (but that would require that callers weren't following the threading rules anyway).
Thanks to @sharwell for noticing the need for this.
> JoinableTask.JoinAsync completes without UI thread

- src/Microsoft.VisualStudio.Threading.Shared/AsyncLazy.cs
We only recently introduced this delegate around the provided value factory, and with that came a small tax. We can make that tax work better for us by moving our cleanup code into it rather than as an extra Task object that must be allocated, along with (likely) an allocated collection to handle the multiple continuations off of the this.value Task.
> Avoid a few more allocations for AsyncLazy execution

- src/Microsoft.VisualStudio.Threading.Shared/JoinableTask`1.cs
- src/Microsoft.VisualStudio.Threading.Tests.Shared/JoinableTaskTests.cs
The JoinAsync method would capture the context of its caller and require it to complete after its underlying JoinableTask completes. This is inefficient since completing should not require this SynchronizationContext.
Theoretically (and as the two new tests demonstrated) it could also lead to deadlocks (but that would require that callers weren't following the threading rules anyway).
Similar to #69 but applies to the derived `JoinableTask<T>` class whereas the former PR only applied to the base `JoinableTask` class.
Fixes #98
> JoinableTask.JoinAsync<T> completes without UI thread

- src/.editorconfig
- src/Microsoft.VisualStudio.Threading.sln
This file configures most formatting settings in Visual Studio 2017 to follow
StyleCop guidelines, reducing the number of cases where a developer sees a
warning that needs to be fixed.
> Add initial .editorconfig

- src/Microsoft.VisualStudio.Threading.Tests/App.config
Fixes #103
Approach taken from dotnet/roslyn-analyzers#927.
> Allow running tests locally via Test Explorer

- src/Microsoft.VisualStudio.Threading.Shared/JoinableTask+JoinableTaskSynchronizationContext.cs
- src/Microsoft.VisualStudio.Threading.Shared/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading.Tests.Shared/JoinableTaskTests.cs
When `JoinableTaskFactory.Run` is invoked from a background thread, and its delegate captures the `SynchronizationContext` and posts to it from another thread at about the same time as the JTF.Run delegate completes, two race conditions exist:
1. `JoinableTaskSynchronizationContext.Post` checks `this.job!=null` before dereferencing it, but another thread sets it to null between the check and the dereference, leading to `NullReferenceException` being thrown from the `Post` method. This crashes Visual Studio. Issue #114. The fix for this is to capture the field as a local variable first. If the field changes in the middle, that's OK, because a completed `JoinableTask` knows how to transfer posted work to the threadpool or `JoinableTaskFactory`.
1. When `JoinableTask.Post` executes it may …
> Fix two race conditions around JoinableTaskSynchronizationContext.Post

- src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
This adds a slight inefficiency (requiring the threadpool to execute a no-op delegate) in favor of mitigating the risk of deadlocks or very long unnecessary waits due to inlined continuations that precede the one we add.
> Fix WaitWithoutInlinining to not wait for inlined continuations

- src/Directory.Build.props
When building individual projects at the command line, the Debug config is omitted from the output path because `$(Configuration)` hasn't been set by the time `Directory.Build.props` is imported. This fixes that.
> Fix build output folder when config is not specified

- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskFactoryTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestUtilities.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
A few months back we "fixed" some "deadlocks" when callers of `JoinableTaskFactory.JoinAsync` would then call `Task.Wait()` on the returned Task. That is obviously a violation of the threading rules but some legacy code exists that really wants to call `Task.Wait()` on the result of a JTF.RunAsync operation so it was important that nothing in the vs-threading code depended on the UI thread being responsive.
However, that led to several tests becoming unstable. It also made `JTF.Run` and `JT.Join()` more vulnerable to threadpool starvation conditions in that they couldn't complete even with a dedicated thread if the threadpool wasn't immediately available. This PR fine-tunes the `ConfigureAwait(bool)` policy for these awaiting methods so that when run inside (some) JTF delegates they …
> Do not require threadpool to complete UI thread bound work

- src/Microsoft.VisualStudio.Threading.Tests/AsyncManualResetEventTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncManualResetEvent.cs
- src/Microsoft.VisualStudio.Threading/TaskCompletionSourceWithoutInlining.cs
The Task it exposed was not completed immediately after calling TrySetResult when the instance was created with the argument to not inline continuations and running in net45 mode.
> Fix regression in AsyncManualResetEvent

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD002UseJtfRunAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD104OfferAsyncOptionAnalyzer.cs
A recent change to share more code between analyzers led to the ironic regression that VSTHRD002 would mis-fire on the very code it suggests people use.
> Prevent VSTHRD002 from mis-firing on use of JTF.Run

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
If `Foo()` and `FooAsync()` both exist, but both return void, it isn't at all clear how they differ. Therefore VSTHRD103 should not suggest that an async method that calls `Foo()` should instead call `FooAsync()`. For instance, `FooAsync()` may be a fire-and-forget method that executes asynchronously with respect to the caller, which would _not_ be equivalent to the code running before which might handle exceptions and certainly didn't proceed until the work was done.
Fixes #167
> Suppress VSTHRD103 diagnostic when alleged async alternative is not awaitable

- appveyor.yml
- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextNodeTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTestBase.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestBaseTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestUtilities.cs
- src/Microsoft.VisualStudio.Threading.Tests/ThreadingToolsTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock+HangReportContributor.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/InternalUtilities.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask+JoinableTaskSynchronizationContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContextException.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContextNode.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskCreationOptions.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/LightUps.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/Properties/AssemblyInfo.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
This adds most of the desktop-only functionality of the library to the netstandard builds since netstandard2.0 makes the necessary APIs available.
Closes #161
> Add .NET Standard 2.0 target framework

- nuget.config
- src/Directory.Build.props
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading.Tests.Win7RegistryWatcher/Microsoft.VisualStudio.Threading.Tests.Win7RegistryWatcher.csproj
- src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
This resolves the build warnings that appear on 15.3 build agents, such as the following:
> C:\Program Files\dotnet\sdk\2.0.0\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(141,5): warning : File 'C:\projects\vs-threading\obj\Microsoft.VisualStudio.Threading\Release\netstandard1.1\es\Microsoft.VisualStudio.Threading.resources.dll' is not added because the package already contains file 'lib\netstandard1.1\es\Microsoft.VisualStudio.Threading.resources.dll' [C:\projects\vs-threading\src\Microsoft.VisualStudio.Threading\Microsoft.VisualStudio.Threading.csproj]
> Update packages to fix pack warnings

- src/Microsoft.VisualStudio.Threading.Tests/AsyncAutoResetEventTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncAutoResetEvent.cs
The Task returned from this method may never complete in response to a canceled CancellationToken if it is canceled at just the right moment while WaitAsync is still executing. This change fixes that.
Fixes #185
> Fix AsyncAutoResetEvent.WaitAsync(CT) race condition

- doc/analyzers/VSTHRD108.md
- doc/analyzers/index.md
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD108AssertThreadRequirementUnconditionallyTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD108AssertThreadRequirementUnconditionally.cs
The VSTHRD0xx range is for critical analyzers. This is merely an advisory and therefore should be in the VSTHRD1xx range.
> Rename VSTHRD013 to VSTHRD108 and document analyzer

- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
Two issues are fixed in the pull request:
#201
#200
Both are reproduced with new unit tests, and those tests are passing after the fix.
First issue:
CancellationToken.Register will call into the callback immediately, if the cancellation token is cancelled. The current code didn't expect that, and add pending request to the queue after this step, and hope the registered cancellation callback will be called later.  Add code to handle CancellationToken after the lock request is added to the queue.
Second issue:
When a lock is issued in the awaiter before IsCompleted is called, and the cancellation token is triggered before IsCompleted is called. This leads IsCompleted to return true immediately. However, this can be on a thread, which the lock is invalid. GetResult() will throw …
> Fix race condition inside AsyncReadWriteLock when it handles CancellationToken

- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
This so that anyone who uses the threading library automatically gets the analyzers
> Add dependency from Threading lib to analyzers

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.TypesRequiringMainThread.mocks.txt
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
This allows for identifying an entire namespace of types as STA objects, but selectively bringing specific types back into their default free-threaded status. The vssdk-analyzers project can then start marking specific types as free-threaded as they are made so.
> Support ! operator in maintypes data file

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
When A() self-identifies as requiring the main thread, all callers (transitively) are now prompted to do the same.
> Raise VSTHRD010 diagnostics transitively

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD002UseJtfRunAnalyzer.cs
Makes this legal (no diagnostic created):
```csharp
Task<int> t;
t.ContinueWith(t2 => t2.Result);
```
Normally accessing `Task.Result` would produce a VSTHRD002 warning, but in a case like this, it's provably safe because it will never block. 
Fixes #217
> VSTHRD002 should allow Task.Wait() within its own continuation

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
Prior to this change VSTHRD010 would transitively mark all methods that called a method that showed a UI thread requirement, including when leaf methods were async and used `SwitchToMainThreadAsync`. This would then make their async caller have to call `ThrowIfNotOnUIThread()` which of course is silly since their caller doesn't need to know the threading affinity of the async methods they invoke.
With this change, instead of marking all callers of all UI thread requiring methods, we only mark callers of methods that _throw_ if not invoked on the right thread.
Fixes #226
> Fix VSTHRD010 transitivity to not mis-fire when invoking async methods

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs
> Allocate WeakKeyDictionary`2 with smaller initial capacities

- src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/SingleThreadedSynchronizationContext.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
- src/Microsoft.VisualStudio.Threading/InlineResumable.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- `JoinableTaskFactory+MainThreadAwaiter`
- `InlineResumable` (an internal type used by `AsyncLazy<T>`)
- `AsyncReaderWriterLock+Awaiter`
- `AsyncReaderWriterResourceLock+ResourceAwaiter`
This and #243 come together to fully address #235
> Implement ICriticalNotifyCompletion on the rest of the awaiters

- src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
- `NoThrowTaskAwaiter`
- `ConfiguredTaskYieldAwaiter`
- `TaskSchedulerAwaiter`
Resolves some of #235. See that issue for a discussion on the merits of this change.
> Implement ICriticalNotifyCompletion on a few awaiters

- doc/analyzers/configuration.md
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.MainThreadAssertingMethods.mocks.txt
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.MembersRequiringMainThread.mocks.txt
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.TypesRequiringMainThread.mocks.txt
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/build/AdditionalFiles/vs-threading.MainThreadAssertingMethods.txt
- src/Microsoft.VisualStudio.Threading.Analyzers/build/AdditionalFiles/vs-threading.MainThreadSwitchingMethods.txt
This allows us to remove the last hard-coded VS API checks from VSTHRD010.
Fixes #230
> Support for member-level specifications regarding main thread affinity

- src/Directory.Build.props
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.MainThreadSwitchingMethods.mocks.txt
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CodeFixVerifier.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD108AssertThreadRequirementUnconditionally.cs
This will offer to fix most occurrences of a VSTHRD010 violation. 
Nothing is hard-coded, but based on the content of AdditionalFiles, it knows that `JTF.SwitchToMainThreadAsync` can switch the user, and because that isn't a static method it 'searches around' for a static instance of JTF and finds it, then offers to fix this:
```cs
static async Task Foo() {
var shell = await asp.GetServiceAsync(typeof(SVsShell)) as IVsShell;
}
```
with this:
```cs
static async Task Foo() {
await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
var shell = await asp.GetServiceAsync(typeof(SVsShell)) as IVsShell;
}
```
It also will find an instance on `this`, so if the context is an `AsyncPackage`, for example:
```cs
protected override async Task InitializeAsync(System.Threading.CancellationToken …
```
> Add VSTHRD010 code fix provider

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageCodeFix.cs
When an ArgumentSyntax is made up entirely of an ExpressionSyntax that violates VSTHRD010, an InvalidCastException would be thrown by the code fix provider. This fixes that by always preferring the most derived node that matches the span.
If that someday fails as well, we can choose the outer-most or inner-most and then walk the tree till we find what we expect.
Fixes #270
> VSTHRD010 code fix should find the inner-most node for a given span

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Namespaces.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
Type checks and casts are only thread affinitized for COM objects. So do what we can to detect whether the type represents a COM type that we're testing for. If it's pure managed, don't flag that it must be done on the main thread.
Fixes #263
> VSTHRD010 to allow type checks and casts on managed objects

- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
This fixes our analyzer package so that the satellite assemblies are signed. We were packing from `obj` but signing the `bin` copy. Now we pack from `bin` as well.
> Pack signed satellite assemblies

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD109AvoidAssertInAsyncMethodsAnalyzer.cs
...when nameof() is used outside any function.
> Fix NullReferenceException thrown from VSTHRD109

- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
We need a way to allow a customized TaskScheduler for this AsyncReaderWriterLock.  This is the initial change to start the discussion.
Related to #257
> Allow AsyncReaderWriterLock to have a different TaskScheduler

- src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
This makes it easy to avoid a dependency on the UI thread or the threadpool to complete async methods that have very little work to do after a Task completes.
.ConfigureAwait(false) does *not* inline continuations when SynchronizationContext.Current != null (when the antecedent is completed).
.ConfigureAwait(true) does *not* inline continuations unless SynchronizationContext.Current is the same instance from when the continuation was created to when the antecedent completes.
Yet .ConfigureAwaitRunInline() will *always* inline the continuation so long as the TPL feels there is enough stack space available. Otherwise it will fallback to the threadpool.
> Add Task.ConfigureAwaitRunInline extension method

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CodeFixVerifier.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Namespaces.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionCodeFix.cs
This also ensures that code fixes are only offered when the (extension) method that is prescribed as an async substitute is actually available so that the code fix does not lead to a compiler error.
Fixes #287
> VSTHRD103 calls out using IVsTask.Wait() in async methods

- src/Directory.Build.props
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreJTFTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreNonJTFTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreTestBase.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.cs.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.de.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.es.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.fr.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.it.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ja.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ko.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.pl.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.ru.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.tr.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading/MultilingualResources/Microsoft.VisualStudio.Threading.zh-Hant.xlf
- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
- src/Microsoft.VisualStudio.Threading/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading/Strings.resx
Several teams have asked for such functionality and I've helped them implement it themselves each time. This simply packages it up as a ready to use class.
With [NuGet in mind](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetLockService.cs) I wonder if we should fulfill a couple more requirements:
* ~~~Allow passing in a particular JTF instance instead of a JoinableTaskContext?~~~ (I misread the nuget version -- it uses its own so we can too)
* ~~~Allow use of *two* JTF instances?~~~ (The alternate JTF can be used to wrap the call into the `ExecuteAsync` method)
* ~~~Expose `IsLockHeld` property~~~ (no, because `CurrentCount` is exposed, and because `IsLockHeld` is ambiguous between held by the caller vs. held at all).
* …
> Add JTF-aware ReentrantSemaphore class

- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD002UseJtfRunCodeFixWithAwait.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD107AwaitTaskWithinUsingExpressionCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionCodeFix.cs
Removes or consolidates equivalentKey values so that batch fixers actually fix every diagnostic from a given analyzer where a particular resolution is available.
Fixes #277
> Fix bulk code fixes

- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
This enables `EnvDTE` to be recognized as an object that should not be cast without first switching to the UI thread.
> Recognize CoClassAttribute as a likely COM STA object

- doc/analyzers/VSTHRD011.md
- doc/analyzers/index.md
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD011UseAsyncLazyAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD011UseAsyncLazyAnalyzer.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
VSTHRD011 previously would flag `Lazy<Task<T>>` as a deadlock prone pattern, prescribing `AsyncLazy<T>` instead. But some equivalent problems were instead expressed as `Lazy<T>` with a value factory that synchronously blocked using JTF.Run.
This PR expands `VSTHRD011` to report diagnostics on the case of using JTF.Run in the value factory as well so we can avoid deadlocks in more cases.
```csharp
var lazy = new Lazy<int>(delegate
{
return joinableTaskFactory.Run(async delegate { // analyzer flags this line
int result = await SomeAsyncMethod();
return result + 3;
});
});
int value = lazy.Value;
```
Closes #253
> Flag use of JTF.Run in Lazy<T> value factories

- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreJTFTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreTestBase.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
The pattern of:
``` CSharp
this.joinableTaskFactory.RunAsync(async () =>
{
using (this.joinableTaskCollection.Join())
using (await this.semaphore.EnterAsync())
{
await externalOperation();
}
});
```
is problematic in that it explodes the size of the joinable task collection, leading to a large dependency graph and serious performance issues. This PR proposes a fix by:
1. Capture synchronization context
2. Await semaphore _without_ using `JTF.RunAsync`. This requires `ConfigureAwaitRunInline()` (hence step 1).
3. `RunAsync` and restore synchronization context.
Let me know what you think of this change, and if the general concept looks good I will apply it to all of `ReentrantSemaphore` and add unit tests as appropriate.
Another thing to consider, is to change `AsyncSemaphore` to use the …
> Optimize JTF Collection size in ReentrantSemaphore

- src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncLazy.cs
This method embodies the optimization that many existing callers use, where they avoid the JTF.Run call if the value factory has already completed. It also avoids the GetValueAsync call entirely in that case (which goes beyond what externals can do).
> Add AsyncLazy<T>.GetValue(CancellationToken) method

- README.md
- src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyInitializerTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncLazyInitializer.cs
This addresses the need that people have used AsyncLazy<object> for, where the returned value from the value factory was not important.
> Add AsyncLazyInitializer class

- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
This is a change to address the performance issue #318
> Prevent reusing NonConcurrentSynchronizationContext between unrelated locks.

- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskFactoryTests.cs
- src/Microsoft.VisualStudio.Threading/DispatcherExtensions.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
> Add an overload to SwitchToMainThreadAsync that exposes 'alwaysYield'

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
> Add test for field awaited in JTF run delegate

- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/WeakKeyDictionaryTests.cs
.netcoreapp2.0 in particular doesn't release memory within a method just because a local variable is cleared, when in debug builds. This causes our memory leak tests to fail for that config+platform. 
This PR fixes the tests by moving these locals into another method that is not allowed to be inlined.
> Fix memory leak tests on netcoreapp2.0 debug configuration

- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
Without this, analyzers observing cancellation end up re-wrapping the exception and showing errors in Visual Studio.
> Add missing handling for OperationCanceledException in DebuggableWrapper

- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD012SpecifyJtfWhereAllowed.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer.cs
These are correctness rules, not style rules, so diagnostics are equally relevant in generated code and user code.
> Explicitly configure VSTHRD012 and VSTHRD105 for generated code analysis

- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
Addresses some confusion reported in #367
> Explain JTF.SwitchToMainThreadAsync cancellation

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD109AvoidAssertInAsyncMethodsAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD109AvoidAssertInAsyncMethodsCodeFix.cs
This required some of the same code fixer functionality already found in the VSTHRD010 code fixer, so a few chunks of code got moved from that fixer into the Utils class.
There are several tested scenarios, but the crux of the fix is that it changes this:
```cs
async Task FooAsync(CancellationToken ct) {
ThreadHelper.ThrowIfNotOnUIThread(); // VSTHRD109 diagnostic here
await Task.Yield();
}
```
to this:
```cs
async Task FooAsync(CancellationToken ct) {
await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync(ct);
await Task.Yield();
}
```
Note that the code fix automatically finds JTF instance(s) to use (the user picks the one from the fix list), and automatically finds any local `CancellationToken` to propagate into the switch method call.
Closes #316
> Add code fix provider for VSTHRD109

- src/Microsoft.VisualStudio.Threading.Tests/AsyncManualResetEventTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskCollectionTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncManualResetEvent.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs
The `AsyncManualResetEvent.WaitAsync(CancellationToken)` overload doesn't do anything the caller can't do anyway, but I occasionally get questions from folks asking how to do it right with a `CancellationToken`, so adding the overload just makes the API easier to consume.
> Add CancellationToken method overloads

- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreTestBase.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
This change adds this overload to `ReentrantSemaphore`, allowing delegates to more conveniently return values to their caller:
```cs
public ValueTask<T> ExecuteAsync<T>(Func<ValueTask<T>> operation, CancellationToken cancellationToken = default);
```
This introduces the first use of `ValueTask<T>` to the vs-threading library. It allows for alloc-free async methods when they don't yield. `Task<T>` on the other hand, often has to be allocated even if the method didn't yield since `Task<T>` itself is a class.
Closes #401
> Add ReentrantSemaphore.ExecuteAsync<T> overload

- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
This allows us to match the version of the assembly VS is already shipping.
> Target System.Threading.Tasks.Extensions 4.3.0 instead of 4.5.1

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
The issue was when VSTHRD003 recursively drills into the inputs of the return statement of a `Task`-returning method, it may end up needing the semantic model of other documents that define those inputs. But we were using `context.SemanticModel` indiscriminately, and it throws when you pass it a `SyntaxNode` from another document that it wasn't made for.
> Fix VSTHRD003 when field is defined in another document

- azure-pipelines/build.yml
We weren't actually shipping both architecture builds of AsyncDebugTools because one overwrote the other during copying.
> Fix shape of deployables artifact

- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/SingleThreadedSynchronizationContext.cs
This change drops `portable-net45+win8+wpa81` and `netstandard1.1` as target frameworks to the core library.
.netstandard 1.3 is still a target. This effectively drops old PCL-based libraries and Windows 8.x Store app and Windows Phone 8.x support.
The lack of PCL targets removes our need to use the MSBuild.Sdk.Extras, so I've removed that as well.
> Drop support for oldest target frameworks

- src/Microsoft.VisualStudio.Threading.Tests/ThreadingToolsTests.cs
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
This allows elimination of closure allocations in many common cases.
Consider adding an item to an immutable collection. With this change, the item to be added can be passed on the stack, making the lambda 'static', and avoiding a per-call closure heap allocation.
```c#
ImmutableList<T> list;
ThreadingTools.ApplyChangeOptimistically(
ref list, itemToAdd, (list, item) => list.Add(item));
```
This [sharplab example](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQFEAeAHJzkCWA9gHYBqUCBUwANigD4ACADAARMCMA3ALABQApgGYOAJjYBhAQG8BbBR1FMALGwCynABQESMNgQCUbeYrn9FlqVGzwkWrcYC8APgNsnTti0N8LigF9TBWClDjV1MR09A2NQ8ytFADkiSRs7CB0AGjYAKw83fM9vX1Cg/xCKtmAiIlprW0RMpgBWAB4aurcwOBIAY2du3r7HP0tQzvqUtMb7XX0CHNa2+ZzJof7Bth7+nV9x/gCgA=) shows the difference and benefit.
---
I considered having one overload call the …
> Overload ApplyChangeOptimistically to take operand

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
Adds support for declaration pattern matching to VSTHRD010.
This required retargeting analyzers to Roslyn 2.8 (VS 2017 Update 7).
Fixes #375
> Adds support for declaration pattern matching to VSTHRD010

- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
This removes the `in` modifier from the parameter in a newly introduced method.
This I guess is a binary breaking change, but the method itself has only been in place for a few days, so it shouldn't break anyone if we act fast, and it removes a Code Analysis build warning.
The build warning could also be suppressed, but the perf argument for passing in `TArg` by ref is only interesting if `TArg` is a large struct such that we would want to avoid copying. But then we'd need to also stop using `Func<T, TArg, T>` in favor of a custom delegate that also takes the `TArg` as an `in` parameter. So I suspect this `in` modifier was unintentional in the first place.
> Fix CodeAnalysis build warning

- src/Microsoft.VisualStudio.Threading/AsyncAutoResetEvent.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock+HangReportContributor.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/FxCopRules.ruleset
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/LightUps`1.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/NoMessagePumpSyncContext.cs
- src/Microsoft.VisualStudio.Threading/ProgressWithCompletion.cs
- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
- src/Microsoft.VisualStudio.Threading/WeakKeyDictionary.cs
We're getting build warnings about using the old FxCop system. This gets us onto the new one, and resolves the several new warnings we were seeing in the switch.
The changes are all very low risk: implement an interface on an internal type, reorder parameters on internal methods, etc.
> Switch from legacy RunCodeAnalysis to FxCopAnalyzers

- azure-pipelines/variables/SignType.ps1
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
Using SignType=test on hosted agents was breaking most of the test runs
> Don't test sign on hosted build agents

- src/Microsoft.VisualStudio.Threading.Tests/AsyncQueueTests.cs
- src/Microsoft.VisualStudio.Threading/FxCopRules.ruleset
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
I made a few changes for this:
1. Added another couple of checks to reduce the likelihood of the race condition and reduce work where it can be optimized away.
1. Within the task.ContinueWith delegate, I check whether we are executing inline. If we are, we divert the CTR.Dispose call to the threadpool.
1. We only reschedule the work to the threadpool if the CancellationToken hasn't already been canceled, since once it has, there is no need to dispose of the CTR anyway since all the memory has been released. So I added a check to skip the threadpool scheduling where we can.
That last point means that basically the `ThreadPool.QueueUserWorkItem` delegate is dead code, since the *only* caller for `AttachCancellation` right now will never complete the TaskCompletionSource while this method is …
> Fix deadlock in AsyncQueue<T>.DequeueAsync cancellation

- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
Roslyn may have multiple (equivalent) instances for an ITypeSymbol, making the == operator sometimes return false when the Equals method would return true.
> Use Equals method when comparing ITypeSymbol in analyzers

- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
See https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2F.corext%2FConfigs%2Fdefault.config&version=GBlab%2Fd16.1stg&line=287&lineStyle=plain&lineEnd=288&lineStartColumn=1&lineEndColumn=1
@AArnott I noticed this while investigating a [RPS bug](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/833390), not sure if this is the cause, but figured I should fix it anyway.
> Update System.Threading.Tasks.Extensions to 4.5.2 to match VS version

- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestUtilities.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/EmptyStruct.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
- src/Microsoft.VisualStudio.Threading/SingleThreadedSynchronizationContext.cs
- src/Microsoft.VisualStudio.Threading/SpecializedSyncContext.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
- src/Microsoft.VisualStudio.Threading/WeakKeyDictionary.cs
⚠️ While these cases are all readonly today, it is a breaking semantic change to change a `readonly struct` by removing the `readonly` keyword. Any types for which you would like to reserve the right to make the type mutable in the future should be excluded from this change.
With that said, at this point I'm not sure you would actually need to make any changes like this.
> Mark structs as readonly where appropriate

- src/Microsoft.VisualStudio.Threading.Tests/ProgressWithCompletionTests.cs
- src/Microsoft.VisualStudio.Threading/ProgressWithCompletion.cs
Our `ProgressWithCompletion<T>` class's entire value of .NET's own `Progress<T>` class is in our `WaitAsync()` method. But since this method allows the caller to await for work executed previously, and since that work might require the main thread, it should be following the 3rd threading rule by using JTF.RunAsync. It wasn't. And as a result deadlocks could happen if that `await progress.WaitAsync()` call were made inside a JTF.Run delegate.
This change adds a JTF option to the class. Similar to our `AsyncLazy<T>` type, it works with or without. But now that a "with" option exists, our threading analyzers will automatically kick in and suggest all existing users switch to providing a JTF instance if they have one by way of a build warning.
I don't think many people use this type as-is, …
> Add JTF-awareness to ProgressWithCompletion<T>

- src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerState.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
This avoids a memory leak that comes from analyzers being reused across compilations.
Fixes #508
Reviewer notes: The content of the `AnalyzeNode` method is exactly the same. I just moved (and re-indented) the method into a nested class.
> Avoid storing ITypeSymbol beyond the scope of a compilation

- src/Microsoft.VisualStudio.Threading.Tests/AsyncSemaphoreTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
Fixes #521
The 16.4 merge of #520
CC: @sharwell
> Fix AsyncSemaphore bug that lets too many threads enter the semaphore

- src/Microsoft.VisualStudio.Threading.Tests/AsyncSemaphoreTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
Fixes a failure in AsyncSemaphore where cancellation during the call EnterAsync can lead to an incorrectly-claimed semaphore. When the Releaser later releases the semaphore, the semaphore transitions to a state where more than one thread may be allowed to use the semaphore.
Thread 1:
* Cancellation is triggered during the SemaphoreSlim.WaitAsync, which completes synchronously even though the semaphore was not acquired
Thread 2:
* Successfully acquires the semaphore
Thread 1:
* Throws an exception for cancellationToken.ThrowIfCancellationRequested()
* Releases the semaphore when exiting the using block
Thread 3:
* Successfully acquires the semaphore, even though Thread 2 has not released it
Fixes #521
> Check the status of waitTask before assuming a lock was acquired

- azure-pipelines/testfx.yml
- src/Directory.Build.props
Reduces the complexity of adopting Nullable Reference Types by ensuring the same bugs and bug fixes are present locally and in CI.
> Use Microsoft.Net.Compilers for a specific compiler version

- src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- src/Microsoft.VisualStudio.Threading/InternalUtilities.cs
> Avoid C# syntax that's toxic to .NET Native compilers

- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskAndAsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskCollectionTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ProgressWithCompletionTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreJTFTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreNonJTFTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/ReentrantSemaphoreTestBase.cs
- src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs
- src/Microsoft.VisualStudio.Threading.Tests/ThreadingToolsTests.cs
- src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncAutoResetEvent.cs
- src/Microsoft.VisualStudio.Threading/AsyncBarrier.cs
- src/Microsoft.VisualStudio.Threading/AsyncCountdownEvent.cs
- src/Microsoft.VisualStudio.Threading/AsyncQueue.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/ProgressWithCompletion.cs
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
- src/Microsoft.VisualStudio.Threading/TplExtensions.cs
The only public API we're deprecating here is `TplExtensions.CompletedTask`.
Also remove the internal APIs we were using that are redundant.
> Obsolete APIs that are redundant with modern .NET versions

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/ReferencesHelper.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Namespaces.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
> Fix VSTHRD200 when using IAsyncEnumerable

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
The current code only adds items to the collection, and clears it later.  The content is never used.
> Remove unused resourcesAcquiredWithinWriteLock field

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.cs.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.de.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.es.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.fr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.it.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.ja.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.ko.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.pl.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.pt-BR.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.ru.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.tr.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.zh-Hans.xlf
- src/Microsoft.VisualStudio.Threading.Analyzers/xlf/Strings.zh-Hant.xlf
We tried to avoid reporting VSTHRD003 diagnostics for readonly Task fields defined in other projects/assemblies, but failed to do so properly. This fixes that to dramatically reduce false warnings typically associated with precompleted tasks such as `SpecialTasks.TrueTask`.
It also refines the wording in the diagnostic to reduce confusion.
> Remove VSTHRD003 warnings for readonly tasks defined in another assembly

- src/Microsoft.VisualStudio.Threading/ThreadingEventSource.cs
The call to `WriteEvent` must have the same argument types as the parameters of the method with the `[Event]` attribute. The comparison in mscorlib doesn't coerce between enum/int.
Prior to this change, the debugger displays a bunch of messages in the output window:
> The parameters to the Event method do not match the parameters to the WriteEvent method. This may cause the event to be displayed incorrectly.
This is logged in `System.Diagnostics.Tracing.EventSource.LogEventArgsMismatches`.
> Fix logging of mismatched arguments

- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
We had this in 15.x, but sometime lost it in 16.x.
> Add vs-threading dependency on the analyzers

- src/IsolatedTestHost/App.config
- src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock.cs
- src/Microsoft.VisualStudio.Threading/IAsyncDisposable.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
Now doing the most efficient thing is as simple as adding `await` in front of the `using` instead of assigning the releaser to a local variable and manually calling `ReleaseAsync` on it prior to exiting the `using` block.
Usage pattern:
```diff
-using (var releaser = await this.asyncLock.WriteLockAsync())
+await using (await this.asyncLock.WriteLockAsync())
{
-    await releaser.ReleaseAsync();
}
```
I'm considering adding a VSTHRD analyzer to find the old pattern and even offer a bulk code fix to update them.
The change is usually better than the older pattern since it guarantees the async exit path is taken even in exception cases.
> Add `using await` support to ARWL.Releaser

- src/Microsoft.VisualStudio.Threading.Tests/NonConcurrentSynchronizationContextTests.cs
- src/Microsoft.VisualStudio.Threading/NonConcurrentSynchronizationContext.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
This `SynchronizationContext` schedules work on the threadpool in such a way as to ensure that no posted delegate is concurrent with another posted delegate.
It provides a "logically single thread" environment without actually having to create a dedicated thread.
> Add NonConcurrentSynchronizationContext

- azure-pipelines/variables/InsertPropsValues.ps1
This will cause our VS repo packages.props file (or an import) to consume the new version.
> Add InsertPropsValues variable

- src/SosThreadingTools/Commands.cs
When we encounter an exception we should print out the exception details to the debugger console to make diagnosing the failure easier.
> Add debugger console output to !dumpasync when encountering an exception

- src/Microsoft.VisualStudio.Threading.Tests/AsyncSemaphoreTests.cs
- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
`SemaphoreSlim` did not guarantee FIFO ordering, which we had mistakenly taken for granted for years. To date, no violation of this incorrect assumption has been detected, but we want to make a strong guarantee of FIFO ordering so folks can use `ReentrantSemaphore` (which is based on `AsyncSemaphore`) as a JTF-aware queue.
This change is obviously to a core scheduling primitive, so it's super important to get this right, and this is a high risk change. I'm requesting code reviews from several engineers I trust to help mitigate this risk.
Fixes #502
> Re-implement AsyncSemaphore to remove SemaphoreSlim dependency

- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/SyntaxGeneratorExtensions.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD114AvoidReturningNullTaskCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD114AvoidReturningNullTaskAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD114AvoidReturningNullTaskCodeFixTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD114AvoidReturningNullTaskAnalyzer.cs
Fixes #618 and based upon #619 
Tagging @AArnott
>  VSTHRD114: Handle delegate and local functions 

- src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD112ImplementSystemIAsyncDisposableAnalyzerTests.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
When enabling this, we should also change the path of the analyzer assemblies in the package to allow Roslyn to recognize and load the dll for VB language projects as well.
This is necessary because of https://github.com/dotnet/roslyn/issues/43963
> Drop VB support

- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
This allows awaiting a `Task` without losing all but the first of the `InnerExceptions` when it faults.
Besides adding tests for it, I modify an existing test to *use* it since it was failing with a timeout on occasion and I suspect the reason is found in another of the `Task.WhenAll` arguments' failures.
> Add `AwaitExtensions.ConfigureAwaitForAggregateException` extension method

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
This change adds allocation- and lock-free fast paths for completed `JoinableTask` instances for the following members:
* `IsCompleted`
* `JoinableTask.Join` and `JoinableTask<T>.Join`
* `JoinableTask.JoinAsync` and `JoinableTask<T>.JoinAsync`
* `JoinableTask.GetAwaiter()` and `JoinableTask<T>.GetAwaiter()` (and in turn the `GetResult()` methods of each)
> Use lock-free fast paths for completed tasks

- doc/analyzers/VSTHRD112.md
Shouldn't this call `DisposeAsync` or is there some compiler magic happening?
> Update VSTHRD112.md to call `DisposeAsync` on `System.IAsyncDisposable`

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs
Switched GetSymbolInfo to IOperation in VSTHRD010.
In one simple repro, a build that took 46 seconds down to just over 1 second.
Fixes #701: a massive perf issue with VSTHRD010
> Substantial perf improvement for VSTHRD010 analyzer

- src/SosThreadingTools/DumpAsyncCommand.cs
The original Dumpasync doesn't handle ValueTask methods, which are common in these days. This PR is to support it in general case.  
It also improved the workaround code to deal with situations when NGen eliminate the structure in the symbol. The original code may pick up a wrong task, when the state machine happens to have a local variable referencing a task. One sample of it is the DispatchIncomingRequestAsync method inside StreamJsonRpc, which has local variables like resultTask/result, which leads the original code to work incorrectly.
> Fix the dumpasync common to handle general ValueTasks.

- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
This PR is to fix a typo in the code, which prevent code to take a short-cut when it finds necessary nodes. It makes a performance problem in VS worse.
> Fix a typo in the JTF dependency computation code.

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
Reuse the existing WeakSelf, instead of allocating another weak reference item.
> Minor: reuse existing WeakReference of the JoinableTask

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- src/Microsoft.VisualStudio.Threading/ThreadingEventSource.cs
This is still in a draft of the current thought. The idea is to delay scanning the JTF dependency graph to potentially patch the dependency computation for disconnected circular dependency loop to a much later time. That includes:
1, when we need a correct answer for IsMainThreadBlocked check for current task
2, when main thread scans the tree to find work: it would remove the optimization for the first request when we know the dependency is up to date, but we also get the information during the scanning, and we take advantage of that to reduce repeated work.
3, when SwitchToMainThread is raised in a background task, this is not an essential point, but we try to do so the computation is more likely to happen in the background thread.
Need more testing, but bring up the PR for preview.
> Try to reduce performance overhead when we remove a JTF dependency

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskCollectionTests.cs
When a JTF task is fully completed, it removes itself from the dependency graph. However, the current logic only reduces ref-count by 1 on the parent side, and may leave it in the graph. (Which is a weak-reference table, so it will be GCed eventually.)
It looks like the code will maintain sync-blocking task chain of a completed task empty, so I could not find a way that this flaw logic actually leads into any corruption, but I still think it is worth to fix. It would be a problem if we move away from the weak-reference dependencies table in the future.
> JoinTillEmptyAsync hangs for ref-counted JTF collection

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
In the JTF implementation, we don't include dependencies of a completed task in the ref-count tracking part, but includes them when scanning the dependencies directly. That inconsistency can lead dependency tracking data structure to be corrupted, and leads into IsMainThreadBlocked to return true for completed main thread tasks.
A new unit test was added to repro this problem, and also include changes to fix them. This change will stop dependency scanning on completed task node.
It doesn't look like any existing unit test actually depending on this behavior.
> An inconsistence whether dependencies of completed tasks should be included leads corrupted data structure

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
1, prevent allocating an empty set when we clean up a synchronized task.
2, adjust condition check orders
3, prevent OnQueueCompleted to run twice.
4, some renaming & clean up expired comments.
No functional impact.
> Minor code cleanups & improvements

- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
Instead of doing another Task.Yield(), just use existing built-in function to ensure it happens once.
The primary goal is to prevent going through the UI thread dispatch queue twice. The VS file watcher is especially busy to send lots of requests, which are often blocked due to some are on the UI thread. This one is just to reduce unnecessary task yield during that code path.
> Prevent going through UI thread pending queue twice

- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
This unit may crash under race conditions, because it may release outer lock before releasing the inner one. It is considered to be fatal errors in the exclusive lock handling code path.
> ensure releasing inner lock before releasing the outer one.

- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextNodeTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
I talked about this during a discussion of using this to set task priority or capture slow stacks.
The original MainThreadBlocking check can be slow, and requires a global sync lock. That makes it not suitable to be used in hot paths. We already notice it to pop up in some slow perf traces. 
The new one is lock free, and doesn't check a few special conditions. Notably, under those conditions the new function would return wrong values:
1, the UI blocking task disjoins some tasks after certain condition is reached. The new method usually will return correct value. However, it does return incorrect value, if there are some circular dependencies, and the cleanup code can be delayed. If this check is done between that time frame, it can be false positive. (This was done to reduce repeating …
> Provide a faster but less accurate way to check whether the current task blocking UI thread

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD110ObserveResultOfAsyncCallsAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerState.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
Fixes #774:
Added functionality:
- recognizing `ConfiguredTaskAwaitable` (returned by `ConfigureAwait` on `Task`)
- recognizing custom awaitable implementation
Fixes #775:
Added functionality:
- recognizing `ValueTask`
- recognizing `ConfiguredValueTaskAwaitable` (returned by `ConfigureAwait` on `ValueTask`)
---
I dared to fix both issues in single PR since #775 was basically just about adding tests and `ConfiguredValueTaskAwaitable`.
> VSTHRD110: trigger on ConfigureAwait, recognize ValueTask

- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
Strictly speaking this is not necessary, as an exception would be thrown to the caller and no lingering adverse effects to the state of `JoinableTaskContext` are left behind. But we find this change useful because this is scheduling code and should be very reliable. Recently an `OutOfMemoryException` was thrown from this code (in a process with plenty of memory) and led other code to hang because it didn't expect JTF itself to fail. See #843 for more info on that.
**Validation**
I tested this crashes the process with the faulting callstack intact (i.e. not unwound) by manually adding a `throw new OutOfMemoryException();` near where we allocate a `WeakReference<T>`. 
Automated tests aren't effective here because the if exercised, the new code would crash the test runner. And anyway forcing …
> Crash the process on unexpected failures when creating a `JoinableTask`

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpUtils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpVSTHRD114AvoidReturningNullTaskAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD114AvoidReturningNullTaskCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic/VisualBasicUtils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic/VisualBasicVSTHRD114AvoidReturningNullTaskAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/AbstractVSTHRD114AvoidReturningNullTaskAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/LanguageUtils.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD114AvoidReturningNullTaskAnalyzerTests.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD114AvoidReturningNullTaskCodeFixTests.cs
VSTHRD114 now ignores C# methods returning `Task?`
Converted VSTHRD114 to an abstract base class in order to use LanguageUtils.
This implementation uses syntax nodes to detect the nullable return type, which means the Roslyn CodeAnalysis does not need to be upgraded.
It prevents VSTHRD114 warnings on cases like these:
```
public Task? GetTask()
{
return null;
}
public Task<int>? GetTaskOfInt()
{
return null;
}
public Task<object?>? GetTaskOfNullableObject()
{
return null;
}
public void LocalFunc()
{
Task<object>? GetTaskObj()
{
return null;
}
}
```
But it doesn't prevent warnings for anonymous functions or lambdas, like:
```
public void StillProducesWarning()
{
Func<Task?> func = () =>
{
return null;
};
}
```
If and when the Roslyn upgrade happens the implementation can be simplified to …
> Suppress reporting VSTHRD114 diagnostic on `Task?` returning methods

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD110ObserveResultOfAsyncCallsAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
VSTHRD110 now detects a ConditionalAccessExpressionSyntax parent of the invocation.
Closes #772
> Update VSTHRD110 to handle conditional access expressions

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
VSTHRD003's AnalyzeAwaitedOrReturnedExpression now detects if the invocation is wrapped inside (possibly multi-levels of) parentheses and if necessary drills-down to get the invocation expression syntax.
Closes #849
> Better handling of parenthesized expressions in VSTHRD003 

- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
The PostToUnderlyingSynchronizationContextCallback property closure was incorrectly keeping the `result` object alive.
> Fix for #515 

- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
Replaced the condition checking whether `this.job` exists with an assert (like is used elsewhere), and removed the #pragma that disabled the CS8602 warning.
My reasoning is that `SingleExecuteProtector` can only ever be constructed with a non-null job (validates with `Requires.NotNull`) and the job is only set to null when `TryExecute` succeeds. Therefore if TryExecute reaches line 1230 then the job will exist.
Closes #544
> Remove dead, buggy code

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.MembersRequiringMainThread.mocks.txt
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
VSTHRD010 now recognizes when struct members require the main thread.
In addition, some minor fixes for three VSTHRD010 Cast unit tests where the test code was using `class` instead of `interface`.
Closes #456
> VSTHRD010 now recognizes when struct members require the main thread

- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
Fixes #883
Moving the typecast up into the if-condition so it can be leveraged for the Contains-check. When the interface is not a `JoinableTask` it can't be in the `HashSet<JoinableTask>` so you can just skip the branch in this case.
Not doing this means there is a type-mismatch between the `HashSet<JoinableTask>` and the variable you're checking (`IJoinableTaskDependent`) which causes C# to pick the LINQ `Enumerable.Contains` extension over the `HashSet.Contains` member.
> Make use of fast HashSet.Contains check

- azure-pipelines/dotnet.yml
- test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
.NET Core 2.1 falls out of LTS support on August 21, 2021. No reason to continue targeting it with new versions of this library.
> Drop .NET Core 2.1 support

- src/Microsoft.VisualStudio.Threading/ReentrantSemaphore.cs
This is called inside and outside of the semaphore and is unneeded lookup. Saw in a high contention trace with file watcher.
> Avoid reading resource unless needed

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpCommonInterest.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs
Closes #693 (I think there's a typo in which it refers to VSTHRD103 but the warning comes from VSTHRD002)
VSTHRD002 now checks if the task has completed via `Task.WhenAll` prior to the problematic member access (e.g. `Result`, `Wait`, `GetResult`), and that the task variable has not been used in a way that would invalidate this test.
**No longer produces VSTHRD002 warnings**
```
var task1 = Task.Run(() => 1);
var task2 = Task.Run(() => 2);
await Task.WhenAll(task1, task2);
return task1.Result + task2.Result;  // No warnings
// Or GetAwaiter().GetResult()
```
```
var task1 = Task.Run(() => 1);
var task2 = Task.Run(() => 2);
var task3 = Task.Run(() => 3);
var task4 = Task.Run(() => 4);
await Task.WhenAll(task1, task2);
int val = task1.Result + task2.Result;  // No warnings
// Use of task3 / …
```
> VSTHRD002 no longer warns on Task.Result/Wait/GetResult/etc after Task.WhenAll (in cases where proved to be safe)

- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
Added a timeout to `NegatableTypeOrMemberReferenceRegex` and `MemberReferenceRegex` to prevent a CPU hang when given input that causes (what I believe to be) very expensive regex backtracking.
Incidentally, some invalid input causes a hang but other invalid input just causes a no-match (as expected).
These cause a hang (or timeout when the Regex is given one):
```
[Microsoft.VisualStud]FooBar
[Microsoft.VisualStudio]FooBar
[aaaaaaaaa.bbbbbbbbbb]FooBar                                            <-- 9 'a' then 10 'b'
```
But the following do not hang and instead return a Regex with no match (as expected).
```
[Microsoft.VisualStu]FooBar
[aaaaaaaaa.bbbbbbbbb]FooBar                                             <-- 9 'a' then 9 'b'
```
Maybe there's something internal to Regex which changes its …
> Avoid compiler hang from invalid text in AdditionalFiles

- src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs
It leads slowdown during solution closing time.
On my local testing trace during closing Roslyn, this can lead 0.5s delay during solution closing time inside:
All tracking tasks are UI thread background tasks. This extra delay is caused by the code requires an extra thread pool dependency, which hits the problem due to thread pools are busy serialize DTBB caches (and a few other clean-up tasks), this block waiting would run to scheduling problems.
@davkean to aware of this change.
> Fix an unnecessary thread pool dependency when waiting JTF collection.

- nuget.config
- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpUtils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD010MainThreadUsageCodeFix.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
This exposes a regression in Roslyn where an existing code fixer broke.
Fixes #861
> Update Microsoft.CodeAnalysis to 3.11.0 in analyzer tests

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/Microsoft.VisualStudio.Threading.Analyzers.CSharp.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
Presently, only methods and properties are handled.
Caveat: only += and -= are handled - raw event accesses didn't fit nicely, since there's no method invocation, and didn't seem high-priority (since they can only occur within the declaring type).
> Extend member access analysis to events

- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
The repro is a very particularly timed race between a timer thread and disposal on another thread. As such, no test can reliably repro it except with careful scheduling under a debugger.
1. A contested enter request is made of the `AsyncSemaphore` that includes a timeout.
1. The timeout expires and `CancellationHandler` is invoked. The `WaiterInfo.Trigger.TrySetCanceled` call succeeds. This thread is now suspended, before it enters the lock on `AsyncSemaphore.syncObject`.
1. Another thread calls `AsyncSemaphore.Dispose()`, which runs to completion.
1. The timeout thread now resumes, acquires the lock and tries to remove its `WaiterInfo.Node` from the `LinkedList`, but the `LinkedList` was already cleared in `Dispose`, so an exception is thrown.
The fix is simply to clear the …
> Avoid internal exception on timeout of AsyncSemaphore request that races with disposal

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock`2.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterResourceLockTests.cs
We noticed web project code gets a project property value (through a rule), then fires an internal event. One of the event handler JTF.Run and switches to the UI thread. It blocks other project code happens to read the project state at the same time due to the special task continuation deadlock.
The change here takes advantage of the logic in the task library, which spins off async continuation first, then calls other continuations in sequence. The logic here is that we join existing computation in async way to prevent this type of deadlock, and let the first continuation keeps the original behavior to reduce potential perf impact.
It is related to a VS deadlock devdiv-1412808.
> Fix a task continuation hang related to project lock.

- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
There is no point in using `ManualResetEventSlim` if we want to only get its `WaitHandle`.
> Use `ManualResetEvent` on `AwaitExtensions.WaitForRegistryChangeAsync`.

- azure-pipelines/release.yml
- doc/dumpasync.md
- src/SosThreadingTools/SosThreadingTools.csproj
Also publish the nupkg with the same payload to the internal WinDBG Gallery.
> Publish SosThreadingTools with github releases

- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.1/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
This makes `await someSyncContext;` work as expected.
> Add `SynchronizationContext.GetAwaiter` extension method

- src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
This avoids calling `CancellationTokenRegistration.Dispose` while holding a private lock in EnterAsync. There is one remaining case where we may hold a lock while calling it, but that's in the inlined case of EnterAsync and CTR will have its default value, and thus could not have anything to block on.
The problematic case that we're fixing is when the token is canceled while EnterAsync is executing between where the CTR is assigned and where we called `info.Cleanup()`. In such a case, we would deadlock because Cleanup would wait for handlers to complete but the handler is waiting for the lock.
There is no unit test change as part of this because the race condition is so very narrow that we couldn't write a unit test that would reliably hit it. However, I did temporarily make a code change …
> AsyncSemaphore fix for deadlock in narrow cancellation race condition

- azure-pipelines/dotnet.yml
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
- src/Microsoft.VisualStudio.Threading/Dgml.cs
- src/Microsoft.VisualStudio.Threading/DispatcherExtensions.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContext+HangReportContributor.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- src/Microsoft.VisualStudio.Threading/net5.0-windows/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net5.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net5.0/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net5.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/DispatcherExtensionsTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- test/Microsoft.VisualStudio.Threading.Tests/SingleThreadedTestSynchronizationContext.cs
- tools/Install-DotNetSdk.ps1
This allows .NET 5.0 Windows targets to consume an assembly that includes WPF types such as `DispatcherExtensions`.
net5.0 contains all the same public APIs that netcoreapp3.1 does.
net5.0-windows contains all the same public APIs that net472 does.
> Add net5.0 and net5.0-windows TFMs

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
Prevent creating two task waiting chains when AsyncLazy.GetValueAsync is called. Especially when a cancellation token is being used, we don't need register cancellation token twice. A single task waiting chain would make dump analysis simply (otherwise, it is hard to link the JTF join chain and task waiting chain together.)
Note: this change will help to investigate some issues like excessive amount of tasks waiting for AsyncLazy. Because the current code chains JTF and task waiting separately, it is much harder to connect the JTF and waiting task together. When there are huge amount of waiting tasks, this code would make them doubled. With this change, it will keep a single task waiting chain to make it easier to investigate. Also, when the cancellation token can be cancelled, we will …
> Prevent creating two task waiting chains when joins AsyncLazy.

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
Reverts microsoft/vs-threading#999
I have concern on this PR to have potential impact to the performance of the product.  The reason:
when this code is executed on UI thread context:
await asyncLazy.GetValueAsync().ConfigureAwait(false)
and the inner task of the async lazy completes on a thread pool. Before this code, this continuation doesn't need back to the UI thread, but joinableTask.JoinAsync would need back to the UI thread to complete.  I think it is unnecessary in JoinAsync code, but it will require further changes to get this more complicated.
> Revert "Prevent creating two task waiting chains when joins AsyncLazy."

- src/Microsoft.VisualStudio.Threading/Boxed.cs
- src/Microsoft.VisualStudio.Threading/ThreadingEventSource.cs
There are around 1MB of allocations caused by boxing boolean values when opening up Orchard Core which we can avoid by caching the values.
> Cache boxed bool values to reduce allocation overhead

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs
- src/Microsoft.VisualStudio.Threading/ThreadingTools.cs
This PR is to improve performance of JoinAsync when a cancellation token is not being used.
The reason behind this is JoinAsync will only complete when the task being waited is completed. A completed JoinableTask will remove itself from the graph, so we don't need chain the task inside JoinAsync to clean up the new dependency.
It is more efficiently to do that:
1, removing dependency will need get into the global lock, which is a contention point of the product
2, removing the completed task will cut all dependencies in one operation, which is much efficient than removing dependencies one by one.
This will allow us not to have any new async state machine in that case, and cut off some unnecessary task continuation in the AsyncLazy, when GetValueAsync is called without a cancellation …
> Reduce unnecessary disposing JTF dependencies & task continuations

- src/Microsoft.VisualStudio.Threading/JoinableTask+ExecutionQueue.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/RarelyRemoveItemSet`1.cs
- test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- test/Microsoft.VisualStudio.Threading.Tests/RarelyRemoveItemSetTests.cs
It was found during recently memory Watson bug investigation. When product code creates lots of dependent tasks of AsyncLazy, it can lead huge amounts of arrays to be allocated in the memory, although almost of them are released, they lead GC pressure or gets into LOH in this case.
Although this usage case has its own problem, it appears that the original data structure to hold child->parent relationship by using ListOfOftenOne was no longer suitable after many design changes in this area. It creates a new array when each item is added or removed was the primary reason behind this issue.
I replaced this with a new slightly different data structure, which tries to retain some advantage of the original data structure to be memory efficient when it holds a small amount of data (which is the …
> Improve scalability in the JoinableTask dependency chain

- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net5.0-windows/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net5.0/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.1/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Shipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
We already have IsMainThreadBlocked and IsMainThreadMaybeBlocked. Both APIs indicate whether the main thread is blocked by the caller. 
Sometimes we need to know whether the main thread is blocked by anyone using JoinableTaskFactory's several blocked APIs. This change exposes that property.
> Expose a property on whether JoinableTaskContext has any JTF blocking calls on the main thread

- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
IsMainThreadMaybeBlocked return true after the current main thread blocking JTF is completed.
This is a wrong behavior, and leads the method to return wrong value for spin-off tasks, and makes it less usable to detect performance issues.
> Fix IsMainThreadMaybeBlocked to return false value after the main task completed

- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/netcoreapp3.1/PublicAPI.Shipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Shipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
This reverts "Expose a property on whether JoinableTaskContext has any JTF blocking calls on the main thread (#1026)".
This property ended up not meeting the product requirement, and since less is more, we're removing the property before 17.3 stabilizes.
> Remove the JoinableTaskContext.IsMainThreadBlockedByAnyone property

- azure-pipelines/OptProf_part2.yml
- azure-pipelines/vs-threading_OptProf.yml
OptProf profiling workflows are moving away from release pipeline over to DartLab (build) pipelines. The yml file added in the pull request setup the vs-threading repo for OptPorf profiling on DartLab.
> Adding yml file for OptProf profiling workflow

- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD100AsyncVoidMethodAnalyzerTests.cs
> VSTHRD100 detects async void local functions and lamdas

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
These fields are important when looking at hangs/dumps to find relationships between the collection and the tasks they are blocked on. Unhide them so its easy to find them in Locals/Autos.
> Unhide fields from debugger

- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/ReferencesHelper.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
Microsoft no longer services this runtime version, so no one should be using it.
> Drop netcoreapp3.1 TFM

- doc/dumpasync.md
Update dumpasync documentation to explain the case where top frame points to an await call with no other frames present.
> Update dumpasync.md to explain the case where awaited task is completed.

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
This code amplifies ETW trace costs, and makes them into thread pool issues in some traces which leads to more noises in performance tests.
> Prevent sending ETW within a lock

- Directory.Packages.props
- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTokenTests.cs
To enable RPC calls (e.g. JSON-RPC -- not COM calls), we add two new APIs:
1. `string? JoinableTaskContext.Capture()` - returns a token that represents the `JoinableTask` that is currently running, and its tokenized parents.
2. `JoinableTask JoinableTaskFactory.RunAsync(Func<Task>, string?, JoinableTaskCreationOptions)` - applies a token previously obtained from _any_ `Capture()` call (even from another process) so that any `JoinableTask` context that matches _this_ `JoinableTaskContext` object will be applied as a parent to the new `JoinableTask`.
Together, this allows RPC infrastructure to utilize `JoinableTaskFactory` to mitigate deadlocks due to requirements on the same UI thread that would otherwise be undetectable as dependencies due to how RPC runs its own queues, and may weave in …
> Allow obtaining serializable tokens that represent JoinableTasks

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterResourceLock`2.cs
- src/Microsoft.VisualStudio.Threading/CancellableJoinComputation.cs
- src/Microsoft.VisualStudio.Threading/InternalUtilities.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterResourceLockTests.cs
The reader/writer lock implementation always spin off a new task with hardcoded task scheduler to call PrepareResources. It happens in the critical path to access a project in the project system implementation. Most of the time, when evaluation is up to date, this is expected to be a quick check, but the extra thread pool scheduling leads it to be sensitive to thread pool issues. Because of this hardcoded scheduler usage, it defeats the effort to use a priority queue to finish UI blocking tasks when thread pool has been scheduled for many background works. 
The change is to prevent changing the behavior when GetResourceAsync is called on the UI thread, as it may lead new kind of deadlocks.
This is considered to be the reason (at least one reason) why priority queue doesn't seem to work in …
> Try to fix a problem that hardcoded thread schedule defeats the effort to prioritize UI blocking tasks.

- README.md
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/README.md
- src/Microsoft.VisualStudio.Threading/README.md
This prepares us for including README files in each nuget package
> Update and restructure README

- Directory.Packages.props
- azure-pipelines/build.yml
- test/IsolatedTestHost/App.config
- test/Microsoft.VisualStudio.Threading.Tests/AssertEx.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncAutoResetEventTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterResourceLockTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncSemaphoreTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskAndAsyncReaderWriterLockTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/ThreadingToolsTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
- Bump xunit.runner.visualstudio from 2.4.5 to 2.5.0 (#210)
- Bump MicroBuildVersion to 2.0.131
- Bump xunit from 2.4.2 to 2.5.0 (#209)
- Remove `tool run` from `dotnet nbgv` invocation
> Merge latest Library.Template

- src/Microsoft.VisualStudio.Threading/AsyncCrossProcessMutex.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncCrossProcessMutexTests.cs
This adds a more convenient way to execute async code while holding (or waiting for) a mutex.
Mutexes are traditionally very difficult to asynchronously wait for or do async work while holding because they are thread affinitized. This new class creates a dedicated thread to 'own' the mutex while allowing the `AsyncMutex` owner to await for the mutex and run async code on any thread while holding it.
> Add `AsyncMutex` class

- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs
Fixes #805
`DisposeAsyncCore` is recommended in https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#the-disposeasynccore-method and as such I believe there should be no warning for the special case.
Though @sharwell mentioned that the name might not be final [here](https://github.com/microsoft/vs-threading/issues/805#issuecomment-800553086). But it's been 2.5 years so my guess is that the topic is not especially hot since nothing has seemingly happened since then.
> Make `VSTHRD200` ignore `DisposeAsyncCore`

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
> Emit VSTHRD003 warning when awaiting on foreign tasks from properties

- src/Microsoft.VisualStudio.Threading.Analyzers/AbstractVSTHRD004AwaitSwitchToMainThreadAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD004AwaitSwitchToMainThreadAsyncAnalyzerTests.cs
> Fix VSTHRD004 mis-fire on `NoThrowAwaitable()`

- Directory.Packages.props
- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD103UseAsyncOptionAnalyzer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD103UseAsyncOptionCodeFix.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/VisualBasicCodeFixVerifier`2+Test.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/VisualBasicCodeFixVerifier`2.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs
VSTHRD103 should flag violations amidst use of `?.` expressions
Fixes #1235
Also workaround roslyn analyzer and xunit version , which only shows up when failures occur.
> VSTHRD103 should flag violations amidst use of `?.` expressions

- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD200UseAsyncNamingConventionCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs
> VSTHRD200 catches local function naming

- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD111UseConfigureAwaitCodeFix.cs
> VSTHRD111: Offer `.ConfigureAwait(false)` as the first code fix

- src/Microsoft.VisualStudio.Threading.Analyzers/AbstractVSTHRD012SpecifyJtfWhereAllowed.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD012SpecifyJtfWhereAllowedTests.cs
> Fix VSTHRD012 false positive due to inaccessible overloads

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD103UseAsyncOptionAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
This prevents false positives in synchronous local functions that appear within async methods.
Fixes #1003
Closes #881
> Analyzer fixes

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpUtils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
When integrating into the VS repo, recent enhancements to VSTHRD003 made insertion of the new analyzers problematic. In particular, two patterns were quite common and arguably should be allowed:
- Awaiting on the `JoinableTask.Task` property on the result of a `JoinableTaskFactory.RunAsync` method call. In general, if a method returns an object, awaiting one of that object's properties *might not* be fair game, but it seems more likely than not. So in this change, that is now allowed.
- Awaiting a `TaskCompletionSource<T>.Task` property on a TCS that was created in that same method. Test methods often do this. Awaiting a TCS.Task property is never guaranteed to be safe as far as analyzers can tell (though the 3rd threading rule can make it safe), and when common patterns appear that are …
> Fix VSTHRD003 to allow for awaiting more Task properties

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
This allows value factories to identify their own code blocks that won't be awaited on and therefore shouldn't trigger reentrancy detection.
> Add `AsyncLazy<T>.SuppressRelevance()` method

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
This pull request to the Microsoft.VisualStudio.Threading.Analyzers.CSharp codebase includes modifications to the `AnalyzeAwaitExpression` method to support returning members of a parameter in a lambda, as well as new tests to verify that warnings are not reported in specific scenarios involving awaiting task properties and returning tasks from lambda arguments.
Main changes:
* <a href="diffhunk://#diff-301533a39b07cca182e799e5029a05ff29ba4d28833d62c1eda305aa223a7e94L198-R222">`src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs`</a>: Modified the `AnalyzeAwaitExpression` method to allow returning members of a parameter in a lambda.
* <a href="diffhunk://#diff-14f9e94958e14aa9b5e8f1a2b716634569ad207fdba2fc53d28d6102532ce9bdR1313-R1335">`test/Microsoft.V …
> VSTHRD003 analyzer false positive fixes

- src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
We already avoided such cases when the creating method was synchronous, but we missed the async case. This came up when trying to update the analyzers version used by the VS repo.
> Avoid VSTHRD003 diagnostic for properties on objects created by async methods

- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj
- src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
- Microsoft.Win32.Registry got added to the .NETCoreApp shared framework with .NET 5.
- System.Threading.Tasks.Extensions has been part of the shared framework since I believe .NET Core 2.0.
- Microsoft.Bcl.AsyncInterfaces since .NET Core 2.1.
Don't reference these packages on .NETCoreApp to reduce the dependency graph and with that potential CVEs / CG warnings.
> Don't package reference inbox assemblies on .NETCoreApp

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
This allows folks to opt-out of the recursive detection altogether, such that `AsyncLazy<T>.SuppressRelevance()` isn't required (though that call would still carry out the JTF suppression function).
> Add `AsyncLazy<T>.SuppressRecursiveFactoryDetection` property

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
`AsyncLazy<T>` had been clearing the `JoinableTaskFactory` field as soon as the value factory had completed. But with the introduction of `DisposeValue()`, we have a subsequent need of the JTF object to avoid deadlocks.
> Fix hang in `AsyncLazy<T>.DisposeValue()` when `T : IAsyncDisposable`

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
Asking nested lock was not considered to be costly, but sending extra ETW event makes them to pop in performance traces. Since they don't provide much value to understand those traces, we should suppress them.
(Note: we don't send ETW when lock is released, so there is no work there.)
The reason behind this change is that this specific ETW event sometime is the primary delay of certain code path, and sometime could cause incorrect interpreting the trace.
During around 7s solution loading trace, the total thread delay from ETW events is about 1.8s, and this event contributed 0.8s, 2x more than any other events. Because capturing stack of ordinal nested lock does not provide lots of value, i think we should suppress it. It would still send event for all top level locks and when an …
> Skip sending ETW trace event for nested lock which is always granted automatically

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs
…CancellationToken) call.
Those appeared a lot during the solution open time, because some global AsyncLazy doesn't provide value until the blocking loading time ends. And cancellation token is often used to handle the case loading is aborted.
The reason why we didn't eliminate the duplication earlier is the JTF.JoinAsync and task.WithCancellation handles in-middle task continuation differently. The JTF one generally will capture the SynchorizationContext, while the task one would not. The exact performance charcter of the two choices is different. The JTF one prevent additional dependency to the thread pool in some cases, but may add unnecessary dependency to the UI thread in other cases, while the other one is on the reverse side. So eliminating the two chains could impact perf, because …
> Prevent creating two task waiting chains per AsyncLazy.GetValueAsync(CancellationToken)

- src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
> Ensure unique `requestId` values in ETW events

- .github/dependabot.yml
- Directory.Packages.props
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj
This way we're consuming the same version of the dependency whether we're on .NET Framework or the .NET 6 runtime which we also target.
Also drop a couple of unnecessary dependencies from the Analyzers.Tests project.
> Rollback Microsoft.Bcl.AsyncInterfaces to 6.0.0

- src/Microsoft.VisualStudio.Threading/AsyncCrossProcessMutex.cs
This avoids a StackOverflowException when dotnet tracing is turned on.
> Increase `AsyncCrossProcessMutex` stack size

- Directory.Packages.props
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
It was an assembly dependency already, which sneaked in via the CsWin32 package due to a bug in its packaging.
Fixes #1303
> Add System.Memory as package dependency

- src/Microsoft.VisualStudio.Threading/AsyncBarrier.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Tests/AsyncBarrierTests.cs
Also optimize the pre-existing code.
The new overload returns `ValueTask` to leave open the option of optimizing to zero-allocation use via `IValueTaskSource`.
Closes #1329
> Add `AsyncBarrier.SignalAndWait(CancellationToken)` overload

- src/Microsoft.VisualStudio.Threading/AsyncLazy`1.cs
- test/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs
This method was failing to create a JoinableTask dependency link such that a value factory that was already in progress and required the main thread would be able to get it from the `DisposeValueAsync` caller.
Fixes devdiv-2169193
For the record, this fixes a bug that existed since the introduction of this method in 17.8. So while this PR fixes 17.12, I based the fixing commit in the 17.8 version so we can *merge* the fix into any older release if necessary.
> Fix hang in `AsyncLazy<T>.DisposeValueAsync`

- doc/analyzers/VSTHRD115.md
- doc/analyzers/index.md
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/FixUtils.cs
- src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD115AvoidJoinableTaskContextCtorWithNullArgsCodeFix.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx
- src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs
- src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD115AvoidJoinableTaskContextCtorWithNullArgsAnalyzer.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net6.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD115AvoidJoinableTaskContextCtorWithNullArgTests.cs
- test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
The `JoinableTaskContext` constructor unfortunately has a poor design where folks passing in `null` for the `SynchronizationContext` may mistakenly believe that they're getting a no-op instance when they aren't, if `SynchronizationContext.Current != null`.
In this change, I add a method that *definitely* does what they expect.
I also add an analyzer and a code fix provider to help identify code that was likely written with the incorrect expectation to help them switch to the new method which matches their expectation, or suppress the warning with a more clear syntax.
> Add `JoinableTaskContext.CreateNoOpContext()` method

- src/Microsoft.VisualStudio.Threading/JoinableTask.cs
The collection of joinable tasks for which an ID is requested grew forever. The code that should purge completed tasks from the collection was never executing because the `TaskId` property is programmed to return `null` for completed tasks, and we query the property directly *after* setting the task as completed.
The fix then is simple: fetch the TaskId value *first* and *then* set the `JoinableTask` as completed.
@sharwell found this and reports that 179MB was held in memory due to this leak in one dump he investigated.
This fixes a memory leak that impacts versions as far back as 17.6. This PR only applies the fix to 17.12, but the commit itself is based on the original bug so the fix can be merged anywhere necessary.
> Fix `JoinableTaskContext.serializedTasks` memory leak

- loc/lcl/CHS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/CHT/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/DEU/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/ESN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/JPN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/KOR/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/PTB/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/RUS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
- loc/lcl/TRK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240815120037610 to main with localized lcls
> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240815120037610 to main

- src/Microsoft.VisualStudio.Threading/RarelyRemoveItemSet`1.cs
- test/Microsoft.VisualStudio.Threading.Tests/RarelyRemoveItemSetTests.cs
An invalid operation exception was thrown inside JTF logic when it enumerates RarelyRemoveItemSet.
It happens in the middle of loading solution sometime.
> Fix an invalid operation exception when enumerating RarelyRemoveItemSet.

- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs
> Raise VSTHRD002 on improper sync-blocking of configured awaiters

- src/SosThreadingTools/SosThreadingTools.csproj
> Update sos-threading tool to use NET 8 runtime

- src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
> Fix VSTHRD110 false negative in local functions of async methods

- test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
This test was provided by @meziantou in #1158
It isn't clear how to fix this without slowing down the analyzer significantly. As this has not been a highly requested, I'm going to Won't Fix this.
Closes #1158
> Add analyzer test to record a future opportunity

- Microsoft.VisualStudio.Threading.sln
- src/LibraryNuspecProperties.props
- src/Microsoft.VisualStudio.Threading.JointPackage/Microsoft.VisualStudio.Threading.JointPackage.csproj
- src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
This new package has the library, but no analyzers dependency. The analyzers dependency is retained by the original `Microsoft.VisualStudio.Threading` package, along with a new dependency on the `Microsoft.VisualStudio.Threading.Only` package.
This allows consumers like StreamJsonRpc to express a dependency on `Microsoft.VisualStudio.Threading.Only` instead of `Microsoft.VisualStudio.Threading` in order to prevent its downstream users from having threading analyzers applied automatically, which they may not want.
> Create a `Microsoft.VisualStudio.Threading.Only` package

- src/Microsoft.VisualStudio.Threading.JointPackage/Microsoft.VisualStudio.Threading.JointPackage.csproj
Important metadata was accidentally [dropped in #1429](https://github.com/microsoft/vs-threading/pull/1429/files#diff-34192d5e83f5d2671fc9d53d52e5984ef968daa13dbecdb77d94b819afcba4a7) that resulted in consumers getting the analyzers but not the AdditionalFiles that the analyzers need to do their job properly. This change brings this metadata back.
> Fix regression in inclusion of analyzer's built-in AdditionalFiles

- docfx/docs/cookbook_vs.md
This guidance is long outdated.
> Drop CPS-specific threading guidance

- src/Microsoft.VisualStudio.Threading/IPendingExecutionRequestState.cs
- src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
- src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net8.0-windows/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/net8.0/PublicAPI.Unshipped.txt
- src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt
For customized SynchronizationContext implementation, knowing whether a pending request has been completed could allow it to remove completed requests. Because JTF requests are potentially sent to multiple queues, including the JTF internal queue, many of those requests can be processed especially inside low priority or delayed queues. For low priority queue, completed tasks showing up for high memory usages. This new contract provides a way to make improvements.
This is only for advanced scenarios, common JTF consumers would not access the request or have chance to use it incorrectly.
> Add `IPendingExecutionRequestState` interface to expose completion state of `SingleExecuteProtector`

- version.json
This is necessary because we built some 17.14 versions and then rewinded the branch.
> Bump version height of 17.14

- azure-pipelines/build.yml
- azure-pipelines/microbuild.before.yml
- samples/samples.csproj
Our builds recently started failing because binskim was including our recently added sample.dll, and because optprof runs were stale but couldn't run due to the new real signing requirement.
But optprof shouldn't need to be real-signed, and binskim should only scan shipping binaries.
I applied the fixes to Library.Template, and this then merges that in.
> Fix build breaks (via Library.Template update)

- src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs
When a debugger is attached, NotifyOfCrossThreadDependency will freeze the thread to send notification to the debugger. Because this NoMessagePumpSynchronizationContext is heavily used, including nested inside code holding the JTF lock already, this logic to call this debugger notification in a very common code path leads the process being debugged becomes extremely slow when JTF is heavily used.
> remove NotifyOfCrossThreadDependency call inside get_NoMessagePumpSynchronizationContext 
