src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSSDK008UseAwaitInAsyncMethodsAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK001SynchronousWaitAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK002VsServiceUsageAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK003AsyncVoidMethodAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK004AsyncVoidLambdaAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK005AsyncEventHandlerAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK006JtfRunAwaitTaskAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK007LazyOfTaskAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK008UseAwaitInAsyncMethodsAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK008UseAwaitInAsyncMethodsCodeFix.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK009AvoidJtfRunInNonPublicMembersAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK010AsyncSuffixAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK011AvoidImpliedTaskSchedulerCurrentAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK012SpecifyJtfWhereAllowed.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSSDK013OfferAsyncOptionAnalyzer.cs
I found these exceptions while trying to apply the analyzers to several projects in the VS repo.
=> Fix null exceptions thrown from VSSDK012 

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010VsServiceInvocationAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/project.json, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010VsServiceUsageAnalyzer.cs
=> Fix VSTHRD010 to fire on more IVs* scenarios

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD012SpecifyJtfWhereAllowedTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD012SpecifyJtfWhereAllowed.cs
=> Avoid VSTHRD012 diagnostic when instantiating JTF

src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncAutoResetEventTests.cs
=> Fix test that wasn't fully validating a continuation

src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncAutoResetEventTests.cs, src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncCountdownEventTests.cs, src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncQueueTests.cs
=> Test doc fixes and added assertions

src/Microsoft.VisualStudio.Threading.Shared/AsyncReaderWriterLock+HangReportContributor.cs
=> Fix AwaiterMetadata.Equals

src/Microsoft.VisualStudio.Threading.Shared/AsyncReaderWriterResourceLock.cs, src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncReaderWriterResourceLockTests.cs
Fixes #86
Thanks @sharwell for finding the bug.
=> Fix AsyncReaderWriterResourceLock.ctor(bool)

src/Microsoft.VisualStudio.Threading.Shared/AsyncReaderWriterLock.cs
=> Suppress message pump when disposing ARWL locks

src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
This is an efficiency improvement for developer workflow.
=> Disable code analysis on build for debug builds

src/Microsoft.VisualStudio.Threading.Shared/AsyncBarrier.cs, src/Microsoft.VisualStudio.Threading.Tests.Shared/AsyncBarrierTests.cs
Fixes #90 found by @sharwell's code inspection.
I add a test that demonstrated the bug can lead to a hang. Then I fixed it.
=> Fix AsyncBarrier thread safety bug

src/Microsoft.VisualStudio.Threading.Tests/AsyncBarrierTests.cs, src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextNodeTests.cs, src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs, src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs
See individual commit messages for explanations.
=> Fix more unstable tests

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
=> Report VSSDK003 diagnostic for unawaited, external tasks in JTF.Run delegates

src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskContextTests.cs
=> Fix GetHangReportWithActualHang test to assert expected exception

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
=> Stop suggesting use of xunit ThrowAsync for synchronous calls

src/Microsoft.VisualStudio.Threading.Tests/DispatcherExtensionsTests.cs, src/Microsoft.VisualStudio.Threading/DispatcherExtensions.cs, src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
=> Add JTF.WithPriority extension method for DispatcherPriority

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
=> Suppress VSTHRD103 suggestion when it would point at the same method

src/Directory.Build.props
As per https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq
=> Set BaseOutputPath conditionally so LUT works

appveyor.yml, src/IsolatedTestHost/ExitCodes.cs, src/IsolatedTestHost/IsolatedTestHost.csproj, src/IsolatedTestHost/Program.cs, src/IsolatedTestHost/TestOutputHelper.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncAutoResetEventTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncQueueTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs, src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs, src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj, src/Microsoft.VisualStudio.Threading.Tests/TestBase.cs, src/Microsoft.VisualStudio.Threading.Tests/TestBaseTests.cs, src/Microsoft.VisualStudio.Threading.Tests/TestUtilities.cs, src/Microsoft.VisualStudio.Threading.sln
This enables a bunch of GC pressure tests for running on AppVeyor that previously would fail. :smile:
=> Provide GC tests with isolation for greater reliability

src/Microsoft.VisualStudio.Threading.Tests/AsyncAutoResetEventTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs, src/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.ruleset
I believe this previously unstable test is now stable
=> Enable another unit test

src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
Most locks taken by JTF suppress the message pump. But several are missing this important step. This commit fixes that.
Fixes #157
Never mind the indentation changes. The only change I make anywhere in this is adding this code around locks:
```csharp
using (this.Context.NoMessagePumpSynchronizationContext.Apply())
{ 
lock (...) { ... }
}
```
=> Suppress message pump for locks in JTF scenarios

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD012SpecifyJtfWhereAllowedTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD012SpecifyJtfWhereAllowed.cs
=> Suppress VSTHRD012 when APIs use [Optional] on the JTF parameter

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionCodeFix.cs
=> Preserve leading trivia in VSTHRD103 code fix

src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs, src/Microsoft.VisualStudio.Threading/JoinableTask+ExecutionQueue.cs, src/Microsoft.VisualStudio.Threading/JoinableTask.cs, src/Microsoft.VisualStudio.Threading/SyncPoints.cs
=> Fix race in JoinableTask.CompleteOnCurrentThread that can lead to deadlock

src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs, src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
=> Add ConfigureAwait(bool) extension method to Task.Yield()

appveyor.yml, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
=> Fix VSTHRD200 to not suggest renaming Main to MainAsync

appveyor.yml, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CodeFixVerifier.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs
=> Analyzer code fix should not rename Main to MainAsync

src/Microsoft.VisualStudio.Threading/LightUps.cs
=> Guard against ConfigurationErrorsException in net45 build

src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD002UseJtfRunAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010VsServiceUsageAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD011LazyOfTaskAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD101AsyncVoidLambdaAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD102AvoidJtfRunInNonPublicMembersAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD104OfferAsyncOptionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD106UseInvokeAsyncForAsyncEventsAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD107AwaitTaskWithinUsingExpressionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
=> Add help links for analyzers

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/DiagnosticVerifier.Helper.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/build/AdditionalFiles/vs-threading.TypesRequiringMainThread.txt
=> Consider IAsyncServiceProvider as a free-threaded type

src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs, src/Microsoft.VisualStudio.Threading/AsyncReaderWriterLock.cs
When a write lock request is canceled, we need unblock read lock requests.  This change is to fix #252
=> Fix a potential dead lock bug in AsyncReaderWriterLock code

src/Directory.Build.props, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD106UseInvokeAsyncForAsyncEventsAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterResourceLockTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs, src/Microsoft.VisualStudio.Threading.Tests/WeakKeyDictionaryTests.cs, src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs, src/Microsoft.VisualStudio.Threading/JoinableTask+DependentSynchronousTask.cs, src/Microsoft.VisualStudio.Threading/RegistryChangeNotificationFilters.cs
This requires fixing a few issues found by the new version.
=> Update StyleCop.Analyzers to version 1.1.0-beta006

doc/analyzers/VSTHRD109.md, doc/analyzers/index.md, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD109AvoidAssertInAsyncMethodsAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD109AvoidAssertInAsyncMethodsAnalyzer.cs
=> Add VSTHRD109 analyzer to find asserts in async methods

doc/analyzers/VSTHRD004.md, doc/analyzers/VSTHRD110.md, doc/analyzers/index.md, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD004AwaitSwitchToMainThreadAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.cs.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.de.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.es.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.fr.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.it.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ja.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ko.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pl.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.pt-BR.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.ru.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.tr.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hans.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/MultilingualResources/Microsoft.VisualStudio.Threading.Analyzers.zh-Hant.xlf, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD004AwaitSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD110ObserveResultOfAsyncCallsAnalyzer.cs
=> Add VSTHRD004 and VSTHRD010 analyzers

src/Microsoft.VisualStudio.Threading.Tests/AsyncLazyTests.cs, src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs, src/Microsoft.VisualStudio.Threading/AsyncLazy.cs, src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs
=> Finish the final logic of AsyncLazy inline to prevent extra dependency to the thread pool

doc/analyzers/index.md
:memo: CI did not run due to an exclusion listed in **.appveyor.yml**.
=> Update titles in index to match documentation pages

doc/analyzers/VSTHRD001.md, doc/analyzers/configuration.md, src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/build/AdditionalFiles/vs-threading.LegacyThreadSwitchingMembers.txt
=> Allow extensions to the set of legacy thread switching members

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionCodeFix.cs
=> Preserve assertion when fixing VSTHRD103

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
=> VSTHRD003 ignores ConfigureAwait for foreign tasks

.appveyor.yml
This is blocking #365 and #359
=> Configure core.autocrlf=true for CI builds

src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.cs
Resolves https://github.com/Microsoft/vs-threading/pull/339#discussion_r208301184
=> Mark exposed member of internal type as internal

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs
Update to Microsoft.CodeAnalysis.Testing 1.0.0-beta1-63310-01
=> Test API update

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/AdditionalFiles/vs-threading.LegacyThreadSwitchingMembers.mocks.txt, src/Microsoft.VisualStudio.Threading.Analyzers/build/AdditionalFiles/vs-threading.LegacyThreadSwitchingMembers.txt
Resolves https://github.com/Microsoft/vs-threading/pull/339#discussion_r208102168
=> Remove Visual Studio specific members from LegacyThreadSwitchingMembers.txt

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
=> Update VSTHRD200 to recognize ValueTask

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageCodeFix.cs
=> Fix syntax nodes used in VSTHRD010 code fix

doc/analyzers/VSTHRD111.md, doc/analyzers/index.md, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD111UseConfigureAwaitAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Microsoft.VisualStudio.Threading.Analyzers.csproj, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.Designer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Strings.resx, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD111UseConfigureAwaitAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD111UseConfigureAwaitCodeFix.cs
Also remove AsyncUsageAnalyzers dependency since we no longer need it.
Closes #385 
Closes #382
=> Add VSTHRD111 "Use ConfigureAwait" analyzer and code fix

src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs
Fix a couple of intermittent test failures
=> Improve test stability

src/Microsoft.VisualStudio.Threading.Tests/AwaitExtensionsTests.cs
=> Increase timeout for unstable test

doc/analyzers/VSTHRD105.md, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer.cs
=> Suppress VSTHRD105 diagnostic on custom TaskFactory instances

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerBase.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs
=> Fix VSTHRD200 to recognize any awaitable type

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs
=> Enable test with multiple syntax trees

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD010MainThreadUsageAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
=> Don't report VSTHRD010 in operator overloads after thread assertion

src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD012SpecifyJtfWhereAllowed.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer.cs
=> Enable concurrent execution of stateless analyzers

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD100AsyncVoidMethodAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD101AsyncVoidLambdaAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD101AsyncVoidLambdaAnalyzer.cs
=> Include event handlers in VSTHRD100 and VSTHRD101

src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs
=> Reduce allocations on VSTHRD103UseAsyncOptionAnalyzer

src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerBase.cs
Reduce allocations on DiagnosticAnalyzerBase
=> Reduce allocations on DiagnosticAnalyzerBase

src/Microsoft.VisualStudio.Threading.Analyzers/DiagnosticAnalyzerBase.cs
=> Fix recent analyzer regression

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj
Submitting this in preparation for enabling Nullable Reference Types.
=> Update Microsoft.VisualStudio.Validation to 15.5.31

src/Microsoft.VisualStudio.Threading.Tests/TplExtensionsTests.cs, src/Microsoft.VisualStudio.Threading/TplExtensions.cs
=> Allow ValueTask recycling when forgetting them

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
=> Fix VSTHRD003 analyzer exception thrown when a method returns a Task from a field defined in another assembly

src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
=> Improve performance of VSTHRD003 analyzer

src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD001UseSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD002UseJtfRunAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD004AwaitSwitchToMainThreadAsyncAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD010MainThreadUsageAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD011UseAsyncLazyAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD012SpecifyJtfWhereAllowed.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD101AsyncVoidLambdaAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD102AvoidJtfRunInNonPublicMembersAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD103UseAsyncOptionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD104OfferAsyncOptionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD105AvoidImplicitTaskSchedulerCurrentAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD106UseInvokeAsyncForAsyncEventsAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD107AwaitTaskWithinUsingExpressionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD108AssertThreadRequirementUnconditionally.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD109AvoidAssertInAsyncMethodsAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD110ObserveResultOfAsyncCallsAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD111UseConfigureAwaitAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD200UseAsyncNamingConventionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD201CancelAfterSwitchToMainThreadAnalyzer.cs
=> Defer selecting localized analyzer message till we know the culture

doc/analyzers/VSTHRD201.md, src/Microsoft.VisualStudio.Threading.Tests/AsyncReaderWriterLockTests.cs, src/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs
=> Throw synchronously from STMTA if token is precanceled off the main thread

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD003UseJtfRunAsyncAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Types.cs, src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD003UseJtfRunAsyncAnalyzer.cs
- Suppress VSTHRD003 in more completed Task cases
- Enhance VSTHRD003 to catch expression bodied methods that violate the rules
=> VSTHRD003 fixes: more good and less bad

src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/FixUtils.cs, src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD002UseJtfRunCodeFixWithAwait.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD002UseJtfRunAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers/CommonInterest.cs
=> Include WaitAny and WaitAll in VSTHRD002 analysis

src/SosThreadingTools/SosThreadingTools.csproj
=> Fix signing of SosThreadingTools.dll

azure-pipelines/artifacts/deployables.ps1
=> Collect dependencies with SosThreadingTools.dll

src/Microsoft.VisualStudio.Threading.Analyzers.Tests/MultiAnalyzerTests.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
=> Get analyzer tests passing on non-English machines

src/Microsoft.VisualStudio.Threading/AsyncSemaphore.cs
A race condition only showed up in our stress test in CI after the #613 PR test passed.
=> Fix an AsyncSemaphore regression

src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpUtils.cs, src/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD112ImplementSystemIAsyncDisposableAnalyzerTests.cs
=> Fix NullReferenceException thrown by VSTHRD112 for some partial classes

doc/analyzers/VSTHRD002.md, doc/analyzers/VSTHRD112.md, src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD103UseAsyncOptionAnalyzer.cs, src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/VSTHRD010MainThreadUsageCodeFix.cs, src/Microsoft.VisualStudio.Threading/AwaitExtensions.cs, src/Microsoft.VisualStudio.Threading/JoinableTask.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs, src/Microsoft.VisualStudio.Threading/JoinableTask`1.cs, src/Microsoft.VisualStudio.Threading/Microsoft.VisualStudio.Threading.csproj, src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.Threading/netcoreapp3.0/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt, src/SosThreadingTools/SosThreadingTools.csproj, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Helpers/CSharpCodeFixVerifier`2+Test.cs, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD103UseAsyncOptionAnalyzerTests.cs, test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskTests.cs
=> Handle IAsyncEnumerable and ValueTask returning methods in VSTHRD103

src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj
=> Add DevelopmentDependency=true to analyzer package

src/Microsoft.VisualStudio.Threading/JoinableTaskDependencyGraph.cs
That is a piece of logic missing in the recent perf changes. I had a wrong impression that it had been added, but it appeared to be wrong. When a synchronize blocking task is finished, it need clean up tracking data from all isolated islands which may still references to the task. Without this clean-up, it may lead leaking the blocking tasks when we do run into this condition.
=> Clean up synchronous task tracking from disconnected circular dependency islands

src/Microsoft.VisualStudio.Threading.Analyzers/Utils.cs, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD200UseAsyncNamingConventionAnalyzerTests.cs
=> Fix homemade IAsyncEnumerable support for VSTHRD200

src/Microsoft.VisualStudio.Threading/OptProf.targets
=> Turn off partial ngen for Dev17

loc/lcl/CHS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CHS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CSY/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CSY/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/DEU/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/DEU/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.CSharp.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.VisualBasic.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/FRA/SosThreadingTools.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20210910191606647 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20210910191606647 to main

src/SosThreadingTools/SosThreadingTools.csproj, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/Microsoft.VisualStudio.Threading.Analyzers.Tests.csproj, test/Microsoft.VisualStudio.Threading.Tests/Microsoft.VisualStudio.Threading.Tests.csproj
- Bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0
- Bump Microsoft.Diagnostics.Runtime.Utilities
- Bump Microsoft.Diagnostics.Runtime from 2.0.243101 to 2.0.252701
- Bump Microsoft.VisualStudio.Shell.15.0
=> Update several dependencies

src/Microsoft.VisualStudio.Threading/TplExtensions.cs
Thanks to @jdrobison for reviewing the code and drawing my attention to this.
=> Avoid `Tuple` allocation in `ToTask(WaitHandle)` when `CancellationToken` cannot be cancelled

loc/lcl/DEU/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211123170210632 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211123170210632 to main

loc/lcl/CHS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211124170208827 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211124170208827 to main

loc/lcl/CSY/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211126170218241 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20211126170218241 to main

src/Microsoft.VisualStudio.Threading/AsyncQueue`1.cs, src/Microsoft.VisualStudio.Threading/net472/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.Threading/netcoreapp3.1/PublicAPI.Unshipped.txt, src/Microsoft.VisualStudio.Threading/netstandard2.0/PublicAPI.Unshipped.txt, test/Microsoft.VisualStudio.Threading.Tests/AsyncQueueTests.cs
=> AsyncQueue<T>.ToArray() made public (#986)

src/Microsoft.VisualStudio.Threading.Analyzers/VSTHRD100AsyncVoidMethodAnalyzer.cs, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD100AsyncVoidMethodAnalyzerTests.cs
These are already covered by VSTHRD101.
Fixes #1074
=> Don't fire VSTHRD100 for async lambdas/delegates

src/Microsoft.VisualStudio.Threading/JoinableTask.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskContext.cs, src/Microsoft.VisualStudio.Threading/JoinableTaskInternals.cs, test/Microsoft.VisualStudio.Threading.Tests/JoinableTaskInternalsTests.cs
Expose JoinableTaskToken for internal use
=> Expose JoinableTaskToken for internal use

src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/CSharpUtils.cs, test/Microsoft.VisualStudio.Threading.Analyzers.Tests/VSTHRD110ObserveResultOfAsyncCallsAnalyzerTests.cs
Fixes https://developercommunity.visualstudio.com/t/Analyzer-MicrosoftVisualStudioThreadi/10176969
Fixes devdiv-1645072
=> Fix VSTHRD110 failure to handle unobserved tasks in finalizers

src/Microsoft.VisualStudio.Threading.Analyzers.CSharp/VSTHRD010MainThreadUsageAnalyzer.cs
=> Add CompilationEnd tag to VSTHRD010 analyzer

loc/lcl/CHS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/CSY/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/DEU/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20221219132054778 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20221219132054778 to main

loc/lcl/CHS/SosThreadingToolsManaged.dll.lcl, loc/lcl/CHT/SosThreadingToolsManaged.dll.lcl, loc/lcl/CSY/SosThreadingToolsManaged.dll.lcl, loc/lcl/DEU/SosThreadingToolsManaged.dll.lcl, loc/lcl/ESN/SosThreadingToolsManaged.dll.lcl, loc/lcl/FRA/SosThreadingToolsManaged.dll.lcl, loc/lcl/ITA/SosThreadingToolsManaged.dll.lcl, loc/lcl/JPN/SosThreadingToolsManaged.dll.lcl, loc/lcl/KOR/SosThreadingToolsManaged.dll.lcl, loc/lcl/PLK/SosThreadingToolsManaged.dll.lcl, loc/lcl/PTB/SosThreadingToolsManaged.dll.lcl, loc/lcl/RUS/SosThreadingToolsManaged.dll.lcl, loc/lcl/TRK/SosThreadingToolsManaged.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230120121750397 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230120121750397 to main

loc/lcl/CHS/SosThreadingToolsManaged.dll.lcl, loc/lcl/CHT/SosThreadingToolsManaged.dll.lcl, loc/lcl/CSY/SosThreadingToolsManaged.dll.lcl, loc/lcl/DEU/SosThreadingToolsManaged.dll.lcl, loc/lcl/ESN/SosThreadingToolsManaged.dll.lcl, loc/lcl/FRA/SosThreadingToolsManaged.dll.lcl, loc/lcl/ITA/SosThreadingToolsManaged.dll.lcl, loc/lcl/JPN/SosThreadingToolsManaged.dll.lcl, loc/lcl/KOR/SosThreadingToolsManaged.dll.lcl, loc/lcl/PLK/SosThreadingToolsManaged.dll.lcl, loc/lcl/PTB/SosThreadingToolsManaged.dll.lcl, loc/lcl/RUS/SosThreadingToolsManaged.dll.lcl, loc/lcl/TRK/SosThreadingToolsManaged.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230122124950525 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230122124950525 to main

loc/lcl/DEU/SosThreadingToolsManaged.dll.lcl, loc/lcl/ITA/SosThreadingToolsManaged.dll.lcl, loc/lcl/PLK/SosThreadingToolsManaged.dll.lcl, loc/lcl/TRK/SosThreadingToolsManaged.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230123125108526 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20230123125108526 to main

doc/analyzers/editorconfigs/AppWithMainThread.editorconfig, doc/analyzers/editorconfigs/AppWithoutMainThread.editorconfig, doc/analyzers/editorconfigs/JTFFocusedLibrary.editorconfig, doc/analyzers/editorconfigs/README.md, doc/analyzers/editorconfigs/SharedLibrary.editorconfig, doc/analyzers/editorconfigs/Tests.editorconfig, doc/analyzers/index.md, doc/analyzers/installation.md
=> Add documentation on installing and configuring analyzers

.devcontainer/Dockerfile, azure-pipelines.yml, azure-pipelines/dotnet.yml, azure-pipelines/official.yml, azure-pipelines/secure-development-tools.yml, azure-pipelines/variables/InsertVersionsValues.ps1, init.ps1
- Update Dockerfile
- Fix placement of $RestoreArguments construction
- Switch from `MSBuildTreatWarningsAsErrors` to `-warnaserror`
- Fix BinSkim when ApiScan won't run
- Parameterize and add diagnostics to InsertVersionsValues.ps1
=> Merge latest Library.Template

version.json
=> Stabilize 17.7

src/SosThreadingTools/SosThreadingTools.targets
Fix the breaks in official builds due to an unsigned file.
=> Sign the `GalleryManifest.xml` file

loc/lcl/CSY/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.Analyzers.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240816121740894 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240816121740894 to main

loc/lcl/CHS/SosThreadingToolsManaged.dll.lcl, loc/lcl/CHT/SosThreadingToolsManaged.dll.lcl, loc/lcl/CSY/SosThreadingToolsManaged.dll.lcl, loc/lcl/DEU/SosThreadingToolsManaged.dll.lcl, loc/lcl/ESN/SosThreadingToolsManaged.dll.lcl, loc/lcl/FRA/SosThreadingToolsManaged.dll.lcl, loc/lcl/ITA/SosThreadingToolsManaged.dll.lcl, loc/lcl/JPN/SosThreadingToolsManaged.dll.lcl, loc/lcl/KOR/SosThreadingToolsManaged.dll.lcl, loc/lcl/PLK/SosThreadingToolsManaged.dll.lcl, loc/lcl/PTB/SosThreadingToolsManaged.dll.lcl, loc/lcl/RUS/SosThreadingToolsManaged.dll.lcl, loc/lcl/TRK/SosThreadingToolsManaged.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240926115059515 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20240926115059515 to main

loc/lcl/CHS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CSY/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/DEU/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250119124922653 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250119124922653 to main

loc/lcl/ITA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250120125111625 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250120125111625 to main

loc/lcl/CHS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CHT/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/CSY/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/DEU/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/ESN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/FRA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/ITA/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/JPN/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/KOR/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PLK/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/PTB/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/RUS/Microsoft.VisualStudio.Threading.dll.lcl, loc/lcl/TRK/Microsoft.VisualStudio.Threading.dll.lcl
LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250314114720535 to main with localized lcls
=> LEGO: Pull request from juno/hb_f2f230f9-08b4-4714-af00-6fce66aaeb84_20250314114720535 to main
